### ISSUE TITLE
hidden attribute used in third-party code

### ISSUE THREAD

**Issue by nuxodin** [kripod/css-homogenizer#1]
If a third party tries to make his hidden element for example:  
```css
visible:hidden;
display:block;
```
it will fail.

https://github.com/kripod/css-homogenizer/blob/88f90221c5ab3b544aa3ac2befa9328d63c35014/opinionated-base.css#L100

**Comment by kripod** [comment]
Thank you for the feedback! As per the [documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden) of the `hidden` attribute:

> Browsers won't render elements with the `hidden` attribute set.

> Changing the value of the CSS `display` property on an element with the `hidden` attribute overrides the behavior. For instance, elements styled `display: flex` will be displayed despite the `hidden` attribute's presence.

By using `!important`, the latter behavior could be avoided, as it isn't desired in most cases, e.g.:

```html
<div style="display: flex" hidden>
  <p>hello</p>
  <p>world</p>
</div>
```

Setting [`visibility: hidden`](https://developer.mozilla.org/en-US/docs/Web/CSS/visibility) should be done independently from the HTML attribute, as it also [removes the given element from the accessibility tree](https://developer.mozilla.org/en-US/docs/Web/CSS/visibility#Accessibility_concerns).

**Comment by kripod** [comment]
I just came across a site which explains it much better than I did. Here it is, for future reference: https://thisthat.dev/display-none-vs-hidden-attribute

**Comment by nuxodin** [comment]
Thanks for your answer

hidden-attribute: for semantic
display:none: for style

> But the hidden attribute provides better semantic. 

As hidden is for semantic, it should be overwritable to make a transformation for example.

As it is in opinionated, its maybe ok.
But I wouldn't take it out of fear to break third party code.
